services:
  frontend:
    image: escuarch/test-software:frontend-latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    restart: always
    networks:
      - clinica-network

networks:
  default:
    external: true
    name: //RED
